### PR TITLE
"title" attribute in the link to an article

### PR DESCRIPTION
**Pull request by MatthieuSarter**
Added a "title" attribute in the link to an article.
Makes TTRSS more usable on a small windows, allowing to see the complete title of an article in the tooltip, without opening the article.

### CODE REVIEW

**Comment by gothfox** [comment]
a good idea but please wrap it with htmlspecialchars.

**Comment by MatthieuSarter** [comment]
Yep, it would be better...
But for some reason I cannot edit the file again in the pull request, I must have messed something with GitHub... Should I create a new pull request and cancel this one ?

**Comment by gothfox** [comment]
sure its fine with me; i honestly don't know how the pull request system works, I pretty much only click the "merge" button.

**Comment by MatthieuSarter** [comment]
Done

**Pull request closed without merging**
