### PR TITLE
Multi select articles

### PR DESCRIPTION
**Pull request by SkyREgit**
Hello Andrew,
I was trying to do minimum intervention to code. I had been missing that function for long time. 
May be you'll find more elegant way to implement this.

### CODE REVIEW

**Comment by gothfox** [comment]
try pressing tab on them

**Comment by SkyREgit** [comment]
I usually need to select large amount of articles.
For example made search by word(s) and look what i don't needed from search results then selecting more then ten articles in time mark them read then move down to next loaded articles.

**Comment by SkyREgit** [comment]
Sorry forgot to mention that i'm scrolling down search results after selecting first article.

**Comment by gothfox** [comment]
ffs tab does multiselect just try it

**Comment by SkyREgit** [comment]
I've tried, but too i have to tab and hove mouse on each article.
I'm using widescreen mode (text after title, so thiner lines of articles) and don't use Combined feed display.
Titles highlighted in dark scheme.
By the way in you dark scheme were some issues, i need to check with latest trunk.

**Comment by gothfox** [comment]
cb_ids.push(child.firstChild.firstChild.firstChild.firstChild.id.replace("dijit_form_CheckBox_", ""));

this is the line where i stopped reading hth

**Comment by SkyREgit** [comment]
Ok, no problem.

**Pull request closed without merging**
