### PR TITLE
Use Git ident attribute for version

### PR DESCRIPTION
**Pull request by nickbroon**
Working to remove the requirement to have the .git directory as part of the install, so that the update check code works for packaged installations. (See https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.download.mk#L69 for example).
Still to work out a replacement for getting the timestamp from the .git/refs/heads/master, which is really the checkout time, not the date of last commit, at any rate.

### CODE REVIEW

**Comment by gothfox** [comment]
update check still goes by git timestamp on the server side and needs this on the client so i'm not sure what that is supposed to achieve.

unless you're talking about some other updater?

**Comment by nickbroon** [comment]
Yup, this is work in progress. I'm still investigating how to get the local timestamp without needing the git directory after install / runtime.
I was just pointing out it would nice to get the commit timestamp for the most recent local commit fetched, not just the timestamp that git/refs/heads/master was cloned/fetched at.

**Comment by gothfox** [comment]
update system is entirely based on running git, you are better of making a plugin or something for your packaged install and disabling it altogether

the only installations i'm supporting are pretty much vanilla trunk git checkouts so i'm sort of vary of changing update checker that works for some packages which i have no idea what other changes go into

maybe its not such a good idea is what i'm saying

**Comment by gothfox** [comment]
especially since you just wanted to merge literally broken code into trunk which is a huge fucking red flag

**Comment by nickbroon** [comment]
Yikes, my bad, will fix asap.

**Comment by nickbroon** [comment]
Would it be sufficient to check only that ```GIT_VERSION_HEAD != $content["changeset"]["id"])``` in ```check_for_update()``` and not bother with ```GIT_VERSION_TIMESTAMP```?

**Comment by gothfox** [comment]
not really because different head commit - unlike a numeric version or w/e - doesn't mean your client is necessarily older - if you're on a different branch or something it would perpetually prompt you to update

**Comment by nickbroon** [comment]
Does the current update checker cope with different branches? As the current timestamp is simply the date that git/refs/heads/master was cloned/fetched at?

**Comment by gothfox** [comment]
it should work by whatever is currently checked out, i think, but maybe only for master; i'm not sure how it works. master may point wherever since git is distributed so its moot anyway, we need the timestamp

**Comment by nickbroon** [comment]
master is just the name of branch, it has no special significance. .git/ref/heads/ will contain files for each local branch. So the current update check does not cope with different branches, and may display the update icon if you're on another branch and that branch is older than master.
I think simply displaying that you're not running with the commit that matches the commit at HEAD of the remote master, be that behind (not fetched/merged), ahead (made local changes), or on a different branch, would be sufficient.

**Comment by gothfox** [comment]
i routinely am ahead of remote branch and having notifications because of it would be annoying

also like i said i'm not gonna change stuff because of some packages so there's really no point in discussing this in the first place. as far as i'm concerned people not using git do not exist.

**Comment by nickbroon** [comment]
Be clear people who are not checkout on HEAD of master do not exist to you. And your update check doesn't even correctly check this.

**Comment by gothfox** [comment]
oh i'm sure its not ideal given i have little idea how git works internally, it works for me so until someone  comes whining or asks to merge a better system its gonna suffice

obviously some consumer nas i'll never gonna see in my life or w/e you are making packages for is not the target here

**Comment by nickbroon** [comment]
For what it's worth .git/HEAD will identify what is currently checked out. This might be ref/head/<something> or might be some arbitrary other hash they are 'detached HEAD' state.

**Comment by nickbroon** [comment]
I'll work on a new Pull Request for your consideration. My aim will be to have it display the update icon simply if it does not match the remote commit (the only robust and reliable check), while not requiring the .git directory at runtime.

**Comment by gothfox** [comment]
>My aim will be to have it display the update icon simply if it does not match the remote commit (the only robust and reliable check),

smh

have fun but i'm not merging it

**Comment by nickbroon** [comment]
ok, even continuing with the use .git, would you accept a merge that has it simply check the commit hashes match and does not use the timestamp? Or would you prefer

**Comment by gothfox** [comment]
you wanted to not use git, now you want to use git but change stuff anyway, i'm not sure why

**Comment by gothfox** [comment]
if you don't like how updater works wrt your packages just rip it out and patch it to something else, it's a 5 line function; either that or make a plugin.

your configuration is unsupported anyway there's not much point in using tt-rss.org master stuff.

**Comment by nickbroon** [comment]
To be specific I was attempting to avoid the use of the .git directory at execution time, not all use of git.
I can probably rework the packaging to include the .git directory as well, but I was also pointing out some broken assumptions in the current git based checker, and considering how best to fix those.
I currently work from a local branch forked from master that I periodically rebase, and get the update icon despite not being on the 'supported' branch, so for the moment have disabled CHECK_FOR_UPDATES in the config).
I could disable the CHECK_FOR_UPDATES config in the production package instead of adding the .git directory, but it would be nice to have check icon displayed showing that that doesn't match the most recent upstream version.

**Comment by nickbroon** [comment]
WIP, and specifically I still need to test that the version comparison works, but you can see my work at: https://github.com/nickbroon/Tiny-Tiny-RSS/commit/8d90b297e47a53d916b1d429749de6cb1b23c45d
To make sure your local copy of ```include/version.php``` contains the actual hash, as one time operation I think you might have do:
```bash
$ rm include/version.php
$ git checkout -- include/version.php
```

**Comment by gothfox** [comment]
i thought i was clear enough in that i wasn't interested in your changes but i guess you just don't get it

i especially liked that you had to change the update prompt because original wording just wasn't technically correct enough or something it really adds to the picture of an insufferable sperglord with nothing better to do

in short, go away

**Pull request closed without merging**
