### PR TITLE
Add new af_comics filters for four comics

### PR DESCRIPTION
**Pull request by insertjokehere**
Add af_comics filters for:
 * Camp Weedonwantcha
 * Gunnerkrigg Court
 * Lackadaisy Cats
 * Sam and Fuzzy

### CODE REVIEW

**Comment by gothfox** [comment]
thanks for your work but i try not to merge stuff i don't myself use because when the site design changes and stuff eventually breaks i get to read some new comic or whatever and figure out what went wrong

af_comics has a modular design for a reason so i suggest instead you post your additions on the T&P subforum so interested people can install the files themselves, thanks.

**Comment by harpojaeger** [comment]
@gothfox, where can I find the "T&P subforum?  Would like to take a look at the plugins people have made and maybe try my own.

**Comment by gothfox** [comment]
https://tt-rss.org/forum/viewforum.php?f=22

**Comment by harpojaeger** [comment]
Sweet, thanks.

**Pull request closed without merging**
