### PR TITLE
Ignore all but shipped themes

### PR DESCRIPTION
**Pull request by mbrodala**
Now that running from Git master is preferred 3rd party themes should be ignored by default.

### CODE REVIEW

**Comment by gothfox** [comment]
why?

**Comment by zorchenhimer** [comment]
@mbrodala Git ignores untracked files on pull unless there's a conflict, in which case the pull aborts.  This change is pretty pointless.

**Comment by gothfox** [comment]
lol so thats what this was about

op, you are an idiot, don't submit anything ever again.

**Comment by mbrodala** [comment]
Just for the record: I am using Git on a daily base and am very well aware of the possible usecases.

While my suggested change is very valid, I'll refrain from submitting any change to this project ever again.

And since this is not the first time you have resorted to insults to make your point, I'll consider switching away from TTRSS. While the software itself works quite well for me (even bought the Android app) using a software created by an author which calls contributors *idiot* doesn't sit well with me.

BTW: it takes an idiot to recognize an idiot. :-)

**Comment by gothfox** [comment]
cool stuff, thanks for sharing

**Pull request closed without merging**
