### PR TITLE
Hide service git files from web access; add a setting to ignore the root check.

### PR DESCRIPTION
**Pull request by dbanet**

### CODE REVIEW

**Comment by gothfox** [comment]
no fucking way

**Comment by dbanet** [comment]
Not even 404 on ``.git``?

**Comment by gothfox** [comment]
no, and i'll let you figure out why your rule is bad

since you run php as root i think you need all the education you can get

**Comment by dbanet** [comment]
I don't run ``php`` as ``root`` just because there is no such thing as ``root`` on my OS.

There are systems that just return zero on ``getuid`` for POSIX compatibility.

**Comment by gothfox** [comment]
those systems are not supported by tt-rss and never will be

**Comment by dbanet** [comment]
I don't give a shit about your support (you anyway never give any).

**Comment by dbanet** [comment]
My system supports tt-rss, if you ask.

**Comment by gothfox** [comment]
thanks for sharing this useful tidbit, friend

**Comment by dbanet** [comment]
So, after your stupid educational argument is busted, will you fix your ``.htaccess``?

**Comment by gothfox** [comment]
lol are you running tt-rss under os/2

**Comment by gothfox** [comment]
also you still haven't figured out why your rule is bad hth

**Comment by dbanet** [comment]
You are just an arrogant ignorant schmuck. Cya.

**Comment by gothfox** [comment]
have a nice day!

**Pull request closed without merging**
