### PR TITLE
 	Update german translation

### PR DESCRIPTION
**Pull request by HeikoAdams**

### CODE REVIEW

**Comment by shoeper** [comment]
At least at the beginning there is an english instead of german translation.

**Comment by HeikoAdams** [comment]
uh ... what? Should have been fixed with acfec96

**Comment by Art4** [comment]
@heikoAdams could you add the change from #435 please? Do I can close my PR.

**Comment by gothfox** [comment]
so ok to merge then?

**Comment by Art4** [comment]
:+1:

**Comment by gothfox** [comment]
alright

**Pull request merged**
